INSERT INTO
    `keywords` (`id`, `keyword`, `slug`)
VALUES (
        1,
        'PAW-SCRATCHER',
        'paw-scratcher'
    ),
    (2, '小宅生活', 'small-home-life'),
    (3, '經典', 'classic'),
    (4, '骨頭', 'bone'),
    (5, '貓抓板', 'cat-scratcher'),
    (6, '抓板', 'scratcher'),
    (7, '大地', 'earth'),
    (8, '淺棕', 'light-brown'),
    (9, '燕麥', 'oat'),
    (10, '暖白', 'warm-white'),
    (11, '沉穩', 'calm'),
    (12, '深灰', 'dark-gray'),
    (13, '8字', 'figure-eight'),
    (14, '極致', 'ultimate'),
    (
        15,
        '控砂墊',
        'litter-control-mat'
    ),
    (16, '奶茶', 'milk-tea'),
    (17, '落砂墊', 'litter-mat'),
    (18, '砂墊', 'litter-mat-2'),
    (19, '豆腐砂', 'tofu-litter'),
    (20, '奶綠', 'milk-green'),
    (21, '貓咪', 'cat-2'),
    (22, '餐包', 'meal-pouch'),
    (23, '滴雞精', 'chicken-essence'),
    (24, '魚', 'fish'),
    (25, '滋補', 'tonic'),
    (26, '營養', 'nutrition'),
    (27, '鮮雞', 'fresh-chicken'),
    (28, '腸胃', 'digestion'),
    (29, '養護', 'care'),
    (30, '泌尿', 'urinary'),
    (31, '皮膚', 'skin'),
    (32, '免疫', 'immunity'),
    (33, '鮭魚', 'salmon'),
    (34, '保健', 'health-care'),
    (35, '鱈魚', 'cod'),
    (36, '牛肉', 'beef'),
    (37, '保護', 'protection'),
    (38, '牛', 'beef-2'),
    (39, '鰹魚', 'bonito'),
    (40, '烏魚', 'mullet'),
    (41, '健康', 'health'),
    (42, '益生菌', 'probiotics'),
    (43, '消臭', 'deodorizing'),
    (
        44,
        '無痕砂',
        'trace-free-litter'
    ),
    (45, '木薯砂', 'cassava-litter'),
    (46, '貓砂', 'cat-litter'),
    (47, '瞬凝', 'instant-clumping'),
    (48, '貓砂盆', 'cat-litter-box'),
    (49, '砂盆', 'litter-box'),
    (50, 'MOFU', 'keyword-50'),
    (51, '早餐罐', 'breakfast-can'),
    (52, '迷你', 'mini'),
    (53, '無膠', 'gum-free'),
    (54, '鮮嫩', 'tender-fresh'),
    (55, '雞肉', 'chicken-2'),
    (56, '營養罐', 'nutrition-can'),
    (57, '挑嘴罐', 'picky-eater-can'),
    (58, '挑嘴', 'picky-eater'),
    (59, '嫩雞', 'tender-chicken'),
    (60, '鱸魚', 'bass'),
    (61, '鯖魚', 'mackerel'),
    (62, '秋刀魚', 'saury'),
    (63, '全雞', 'whole-chicken'),
    (64, '低敏', 'hypoallergenic'),
    (65, '鴨胸', 'duck-breast'),
    (66, '鴨', 'duck'),
    (67, '鮮甜', 'sweet-fresh'),
    (68, '虱目魚', 'milkfish-2'),
    (69, '寵物', 'pet'),
    (
        70,
        '四季被',
        'all-season-blanket'
    ),
    (71, '藍綠', 'blue-green'),
    (72, '米色', 'beige'),
    (73, '粉', 'pink'),
    (74, '肉泥罐', 'puree-can'),
    (75, '益菌', 'probiotics-2'),
    (76, '綿密', 'creamy'),
    (77, '肉泥', 'puree'),
    (78, '主食罐', 'complete-can'),
    (79, '海味', 'seafood'),
    (80, '鮪魚', 'tuna'),
    (81, '凍乾', 'freeze-dried'),
    (82, '小方粒', 'small-cube'),
    (83, '安心', 'safe'),
    (84, '湯匙', 'spoon'),
    (85, '鮮肉', 'fresh-meat'),
    (86, '生食', 'raw-food'),
    (87, '幼貓', 'kitten'),
    (88, '花草', 'herbal'),
    (89, '條型', 'strip-type'),
    (90, '清新', 'fresh'),
    (91, '森林浴', 'forest-bath'),
    (92, '森林', 'forest'),
    (
        93,
        '低磷罐',
        'low-phosphorus-can'
    ),
    (94, '低磷', 'low-phosphorus'),
    (95, '低蛋白', 'low-protein'),
    (96, '魷魚', 'squid'),
    (97, '腎臟', 'kidney'),
    (98, '青花魚', 'mackerel-2'),
    (99, '米粒型', 'rice-grain-type'),
    (100, '原味', 'original'),
    (101, '專利', 'patented'),
    (102, '砂鏟', 'litter-scoop'),
    (103, '配送箱', 'shipping-box'),
    (104, '溫暖杏', 'warm-beige'),
    (105, '沉靜灰', 'calm-gray'),
    (106, 'JW', 'jw'),
    (107, '指甲剪', 'nail-clipper'),
    (108, '快篩', 'quick-sifting'),
    (
        109,
        '貓砂鏟',
        'cat-litter-scoop'
    ),
    (110, '靜音', 'quiet'),
    (111, '貓隧道', 'cat-tunnel'),
    (112, '可折疊', 'foldable'),
    (113, '隧道', 'keyword'),
    (114, '平板式', 'flat'),
    (115, '低脂', 'low-fat'),
    (116, '南瓜丁', 'pumpkin-cubes'),
    (117, '雞絲', 'shredded-chicken'),
    (118, '元氣', 'vitality'),
    (119, '草飼', 'grass-fed'),
    (120, 'FELIWAY', 'keyword-120'),
    (121, '費洛蒙', 'pheromone'),
    (122, '法國', 'france'),
    (123, '插電組', 'plug-in-set'),
    (124, '補充瓶', 'refill-bottle'),
    (125, '噴劑', 'spray'),
    (126, '鮮食', 'fresh-food'),
    (
        127,
        '土雞',
        'free-range-chicken'
    ),
    (128, '薑黃', 'turmeric'),
    (
        129,
        '時蔬',
        'seasonal-vegetables'
    ),
    (130, '紅石榴', 'pomegranate'),
    (131, '鴨肉', 'duck-meat'),
    (132, '朝鮮薊', 'artichoke'),
    (133, '肉蓉罐', 'minced-meat-can'),
    (134, '鵪鶉', 'quail'),
    (135, '羊肉', 'lamb'),
    (136, '羊', 'lamb-2'),
    (137, '銀養罐', 'silver-care-can'),
    (138, '熟齡貓', 'senior-cat'),
    (139, '鹿', 'venison'),
    (140, '熟齡', 'senior'),
    (141, '野生', 'wild'),
    (142, '頂級', 'premium'),
    (143, '木天蓼', 'silvervine-3'),
    (144, '蟲癭果', 'gall-fruit'),
    (145, '棒棒', 'sticks'),
    (146, '潔牙', 'dental-care'),
    (147, '紓壓', 'stress-relief'),
    (
        148,
        '幼母貓',
        'kitten-and-mother-cat'
    ),
    (149, '母貓', 'mother-cat'),
    (150, '放牧', 'pasture-raised'),
    (151, '鹿肉', 'venison-meat'),
    (
        152,
        '100% Pure',
        '100-percent-pure'
    ),
    (153, '鮮肉罐', 'fresh-meat-can'),
    (154, '火雞', 'turkey-2'),
    (155, '蝦仁', 'shrimp'),
    (156, '扁鱈', 'flatfish'),
    (157, '山野', 'wild-field'),
    (158, '新包裝', 'new-package'),
    (159, '鬆狀', 'flaky'),
    (160, '沙西米', 'sashimi'),
    (
        161,
        '無骨雞',
        'boneless-chicken'
    ),
    (162, '澳洲', 'australian'),
    (163, '羅曼', 'roman'),
    (164, '鵝', 'goose'),
    (165, '乾貓草', 'dried-cat-grass'),
    (166, '貓薄荷', 'catnip-2'),
    (167, '貓草', 'cat-grass'),
    (168, '薄荷', 'mint'),
    (169, '犬用', 'for-dogs'),
    (170, '慢烘', 'slow-baked'),
    (
        171,
        '蔬肉糧',
        'vegetable-meat-food'
    ),
    (172, '鮮蔬', 'fresh-vegetables'),
    (173, '玩具總動員', 'toy-story'),
    (174, '罐罐', 'canned-food'),
    (175, '專用', 'for-cans'),
    (176, '三入組', 'three-piece-set'),
    (177, '迪士尼', 'disney'),
    (178, '綜合組', 'assorted-set'),
    (179, '減壓', 'pressure-relief'),
    (180, '多功能', 'multifunction'),
    (181, '緩衝', 'shock-absorbing'),
    (182, '狗狗', 'dog-2'),
    (183, '強壯', 'strong'),
    (184, '雞腿', 'chicken-leg'),
    (185, '閃亮', 'shiny'),
    (186, '羊腿', 'lamb-leg'),
    (187, '熟齡犬', 'senior-dog'),
    (188, '干貝', 'scallop'),
    (
        189,
        '幼母犬',
        'puppy-and-mother-dog'
    ),
    (
        190,
        '鱉蛋',
        'softshell-turtle-egg'
    ),
    (191, '生肉餐', 'raw-meat-meal'),
    (192, '狗草', 'dog-grass'),
    (193, '栽培盒', 'grow-kit'),
    (194, '汪汪', 'doggy'),
    (195, '生菜', 'greens');