INSERT INTO
    `product_special_tags` (`id`, `tag_ch`, `tag_slug`)
VALUES (1, '幼齡(0~1歲)', 'baby'),
    (2, '成齡(1~7歲)', 'adult'),
    (3, '熟齡(7歲~)', 'senior'),
    (4, '孕期', 'pregnancy'),
    (5, '低敏', 'hypo-allergenic'),
    (6, '挑嘴', 'picky-eater'),
    (7, '低脂', 'low-fat'),
    (8, '低磷', 'low-phosphorus'),
    (9, '低蛋白', 'low-protein'),
    (10, '專利', 'patented'),
    (11, '鮮食', 'fresh-food'),
    (12, '腸胃養護', 'digestion-care'),
    (13, '皮膚保健', 'skin-care'),
    (14, '泌尿保健', 'urinary-care'),
    (15, '毛球保健', 'hairball-care'),
    (16, '關節保健', 'joint-care'),
    (17, '牙齒保健', 'dental-care'),
    (18, '情緒舒緩', 'stress-care'),
    (19, '眼睛保健', 'eye-care');